### ISSUE TITLE
`setup.py` is not working

### ISSUE THREAD

**Issue by Deivitto** [pessimistic-io/slitherin#102]
**Context**: 
OS: ubuntu 22:04
Within: [Docker](https://github.com/Deivitto/auditor-docker)
Packages: If it's needed a list of any type of installed packages let me know

**Steps**:
After doing a basic git clone and then trying to run the setup configuration, well, it fails due to a missing module not in the installation guide. 

- Clone:
`git clone https://github.com/pessimistic-io/slitherin.git ~/.slitherin`

- Setup:
```shell
whitehat@9ce46d60434c:~$ cd .slitherin/
whitehat@9ce46d60434c:~/.slitherin$ ls
LICENSE.txt  MANIFEST.in  README.md  docs  package-lock.json  package.json  setup.py  slitherin  tests
whitehat@9ce46d60434c:~/.slitherin$ cd .slitherin/^C
whitehat@9ce46d60434c:~/.slitherin$ python3.9 setup.py develop --user
Traceback (most recent call last):
  File "/home/whitehat/.slitherin/setup.py", line 2, in <module>
    from slitherin.cli import SLITHERIN_VERSION
  File "/home/whitehat/.slitherin/slitherin/cli.py", line 9, in <module>
    import slither_pess
ModuleNotFoundError: No module named 'slither_pess'
whitehat@9ce46d60434c:~/.slitherin$ python3.9 setup.py develop
Traceback (most recent call last):
  File "/home/whitehat/.slitherin/setup.py", line 2, in <module>
    from slitherin.cli import SLITHERIN_VERSION
  File "/home/whitehat/.slitherin/slitherin/cli.py", line 9, in <module>
    import slither_pess
ModuleNotFoundError: No module named 'slither_pess'
```
Previously this was working as intended, so I guess is due to the last patch

**Comment by ndkirillov** [comment]
Closing as fixed
